### ISSUE TITLE
Sql-explorer generates a migration file on makemigrations

### ISSUE THREAD

**Issue by richardbann** [galaktika-solutions/gStack#39]

**Comment by danieltatrai** [comment]
Belefutottam, mit kéne ezzel kezdeni? Makemigrations elhasal permission denied-al.

**Comment by richardbann** [comment]
Nem tudom. Zoli a githubról installál egy olyan fork-ot, amin ez már javítva van. Csak annak ugye kell egy git az image-ben...

**Comment by richardbann** [comment]
#40 fixes it
